version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      # Mount your local timezone for correct time
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Change this to your timezone
